
# Obstacle Cost Shaping (http://wiki.ros.org/costmap_2d/hydro/inflation)
# distance a circular robot should be clear of the obstacle
# robot_radius: 0.25
# if the robot is not circular
footprint: [[0.25, 0.2], [0.25, -0.2], [-0.25, 0.2], [-0.25, -0.2]] 
# max. distance from an obstacle at which costs are incurred for
# planning paths.


obstacle_range: 3.0
raytrace_range: 2.5

obstacle_layer:
  enabled: true
  observation_sources: laser
  laser: {data_type: LaserScan, clearing: true, marking: true, topic: /scan, inf_is_valid: true}

inflation_layer:
  enabled:              true
  cost_scaling_factor:  5.0  # exponential rate at which the obstacle cost drops off (default: 10)
  inflation_radius:     0.25  # max. distance from an obstacle at which costs are incurred for planning paths.

static_layer:
  enabled:              true

sonar:
  topics: ["/range"]
  no_readings_timeout: 0.0
  clear_threshold: .8
  mark_threshold: 1.5
  clear_on_max_reading: true

# Can we just set up two of these here?
#bump: {
#        data_type: PointCloud2, 
#        topic: mobile_base/sensors/bumper_pointcloud, 
#        marking: true, 
#        clearing: false, 
#        min_obstacle_height: 0.0, 
#        max_obstacle_height: 0.15
#      }

